import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { config } from './config.js';
import * as schema from './schema.js';
fs.mkdirSync(path.dirname(config.dbPath), { recursive: true });
fs.mkdirSync(path.join(config.dataDir, 'images'), { recursive: true });
fs.mkdirSync(path.join(config.dataDir, 'imports'), { recursive: true });
fs.mkdirSync(path.join(config.dataDir, 'backups'), { recursive: true });
export const db = new Database(config.dbPath);
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');
export const orm = drizzle(db, { schema });
const migrationPath = new URL('./schema.sql', import.meta.url);
const fallback = path.resolve('apps/api/src/schema.sql');
db.exec(fs.readFileSync(fs.existsSync(migrationPath) ? migrationPath : fallback, 'utf8'));
export const now = () => new Date().toISOString();
export const id = () => crypto.randomUUID();
